- menu_name: "Tracking"

- name: "RSS"
  url: "http://www.inf.ufrgs.br/ipeanalytics/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "http://www.inf.ufrgs.br/ipeanalytics/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "http://www.inf.ufrgs.br/ipeanalytics/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
